### ISSUE TITLE
シーン遷移のエラー修正

### ISSUE THREAD

**Issue by livestock111** [cordx56/digicre_digigame-expo_1#12]
シーンを前に戻すと起きるエラーの修正

**Comment by al13012** [comment]
@livestock111 これどうやって再現できます？(ゲームプログラム上の操作と，実際のコードがどの辺か)

**Comment by livestock111** [comment]
すみません。
コメントアウトしてもう一度あげ直します。

**Comment by livestock111** [comment]
コメントアウトしたものをあげ直しました。
こんな感じで大丈夫でしょうか。

**Comment by al13012** [comment]
えっと，バグはゲーム起動してからどういう操作(クリックやキー入力など)をすると発生する？

**Comment by livestock111** [comment]
ShopからGameに戻ろうとしたりすると起きます。
Title->Stage->Game->Shop->Game(ここでエラー)という感じです。

**Comment by al13012** [comment]
ということは，
クリック → Enter → 0
で再現？

**Comment by livestock111** [comment]
そのはずだったんですが、今確認したところ、問題なく動いていました。

**Comment by al13012** [comment]
だよね…とりあえずこのissueはcloseしておいて，もし再発したらその時点でのコードをコミットして，そのリンクと一緒にもう一度openしましょう

**Comment by livestock111** [comment]
了解しました。
すみません。
