### ISSUE TITLE
マップ構造の変更に伴う問題

### ISSUE THREAD

**Issue by cordx56** [cordx56/digicre_digigame-expo_1#15]
マップ構造の変更に伴い、以下の関数群が影響を受けました:
MapReader::getBlockID
MapReader::isGoal

this->dynMapDataを直接参照している関数に影響が出ているものとみられます。
this->dynDrawMapDataを参照している関数には影響がありませんでした。

**Comment by al13012** [comment]
あー，そうですね．xとyのindexが逆転してるので…( `dynDrawMapData` には逆転した後のデータを入れてあるので問題ない)
直します
