### ISSUE TITLE
プレイ画面の動作軽量化

### ISSUE THREAD

**Issue by cordx56** [cordx56/digicre_digigame-expo_1#5]
最新のコードでは何故か極端に挙動が遅いので、原因を特定し修正する。

**Comment by al13012** [comment]
@cordx56 5-improve_performance の挙動がどんなもんか見てもらえますか？(こちらの手元だと開発環境のスペックが比較的高いため元のコードでも特に不自由なく動いてしまいました)

**Comment by cordx56** [comment]
以前よりは幾分か速くなった印象がありますが、やはりFPS30程度まで落ちて、かくついてしまいます。
こちらのPCも性能はそこまで悪くないはずですが・・・
元のコードも単体テストの時は軽快に動作していたので、シーン管理側の問題である可能性もあります。とりあえずこちらは動作に必須の部分ではないので後回しで構いません。よろしくお願いします。

**Comment by cordx56** [comment]
一旦5-improve_performanceをマージしました。

**Comment by al13012** [comment]
あー，マージしてしまうのはまぁ構わないと言えば構わないんですが，基本的にPR以外のマージはしない(仮にマージするにしても，自分で(今回であれば5-improve_performanceブランチの)PR出してからマージする)ようにしてください．

また， **どうしても手でマージしたい** という場合は，`git merge 5-improve_performance --no-ff` のようにFast Forwardを切って，マージコミットを付加するようにしてください．

**Comment by al13012** [comment]
ひとまず動作に支障がないということなのでこのissueもcloseします．再発した場合はreopenしましょう．
